name: tapfirst
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  http: ^1.2.2
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_remote_config: ^5.0.3
  firebase_ui_auth: ^1.15.0
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_image.png
